### ISSUE TITLE
Not compatible with jacoco

### ISSUE THREAD

**Issue by iNikem** [pedjak/gradle-dockerized-test-plugin#2]
When I try to use this plugin together with gradle jacoco plugin I get the following error:

```
:portal:spock
java.io.FileNotFoundException: /Users/Nikem/Documents/workspace/plumbr/portal/build/jacoco/spock.exec (No such file or directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
    at org.jacoco.agent.rt.internal_afc1452.output.FileOutput.openFile(FileOutput.java:67)
    at org.jacoco.agent.rt.internal_afc1452.output.FileOutput.startup(FileOutput.java:49)
    at org.jacoco.agent.rt.internal_afc1452.Agent.startup(Agent.java:122)
    at org.jacoco.agent.rt.internal_afc1452.Agent.getInstance(Agent.java:50)
    at org.jacoco.agent.rt.internal_afc1452.PreMain.premain(PreMain.java:45)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:382)
    at sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:397)

```

Without using docker image everything works fine

**Comment by iNikem** [comment]
It seems that build running inside docker container cannot write arbitrary files in project dir. Some of my tests fail even without jacoco if they try to write files.

**Comment by pedjak** [comment]
That should not be the case... by default the version 0.3 mount project dir as the volume. Is plumbr/potral the project dir?

**Comment by iNikem** [comment]
`plumbr` is project's root dir and `portal` is the sub dir. But thinking of it now, may the problem is in my Mac's boot2docker environment. I will try this on pure Linux...

**Comment by pedjak** [comment]
you should mount your Mac user home under the same path within boot2docker.
