### ISSUE TITLE
Can the project be fixed to support Gradle 4.0 version please.

### ISSUE THREAD

**Issue by prdelp** [pedjak/gradle-dockerized-test-plugin#6]
Running this with gradle 4.0 does not work well. 

```
Caused by: groovy.lang.MissingPropertyException: No such property: workerFactory for class: org.gradle.process.internal.worker.DefaultWorkerProcessFactory
        at com.pedjak.gradle.plugins.dockerizedtest.DockerizedTestPlugin.newProcessBuilderFactory(DockerizedTestPlugin.groovy:101)
        at com.pedjak.gradle.plugins.dockerizedtest.DockerizedTestPlugin$_configureTest_closure1.doCall(DockerizedTestPlugin.groovy:70)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:670)
        at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:651)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 27 more
```

**Comment by prdelp** [comment]
Its probably due to https://github.com/gradle/gradle/commit/38b699d996f74ed8f6d45a8bf2c57832bbfca97c#diff-2edc5a9d3815acde69042eaccaa4f24f
